### ISSUE TITLE
ValueError: empty vocabulary; perhaps the documents only contain stop words

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [cdqa-suite/cdQA#215]
**Describe the bug**
```
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    cdqa_pipeline.fit(X=df)
  File "E:\Python\cdQA\cdqa\pipeline\cdqa_sklearn.py", line 86, in fit
    self.retriever.fit(self.metadata['content'])
  File "E:\Python\cdQA\cdqa\retriever\tfidf_sklearn.py", line 75, in fit
    self.tfidf_matrix = self.vectorizer.fit_transform(X)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 1652, in fit_transform
    X = super().fit_transform(raw_documents)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 1058, in fit_transform
    self.fixed_vocabulary_)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 989, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

**To Reproduce**
```
import pandas as pd
from ast import literal_eval
from cdqa.pipeline.cdqa_sklearn import QAPipeline  
from cdqa.utils.converters import pdf_converter

df = pdf_converter(directory_path='E:/books')

cdqa_pipeline = QAPipeline(model='bert_qa_vGPU-sklearn.joblib')
cdqa_pipeline.fit(X=df)   
cdqa_pipeline.predict(X='What is?')
```

**Expected behavior**
Prediction

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by fmikaelian** [comment]
Hi

This is due to our default implementation of the retriever which is based on sklearn's [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html). 

As you can see here, the default value of param `max_df` is 0.85.

https://github.com/cdqa-suite/cdQA/blob/3c65bffc883b9097e8579c67d3f04caf5879dfab/cdqa/retriever/tfidf_sklearn.py#L57

You can override this parameter directly when casting the `QAPipeline()` class, for example setting it to 1 should solve your problem:

```
cdqa_pipeline = QAPipeline(reader='models/bert_qa_vGPU-sklearn.joblib', max_df=1.0)
cdqa_pipeline.fit(X=df)
```

**Comment by ErfolgreichCharismatisch** [comment]
With your code I get

```
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    cdqa_pipeline.fit(X=df)
  File "E:\Python\cdQA\cdqa\pipeline\cdqa_sklearn.py", line 86, in fit
    self.retriever.fit(self.metadata['content'])
  File "E:\Python\cdQA\cdqa\retriever\tfidf_sklearn.py", line 75, in fit
    self.tfidf_matrix = self.vectorizer.fit_transform(X)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 1652, in fit_transform
    X = super().fit_transform(raw_documents)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 1058, in fit_transform
    self.fixed_vocabulary_)
  File "E:\Anaconda\envs\frageantwort\lib\site-packages\sklearn\feature_extraction\text.py", line 989, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

**Comment by andrelmfarias** [comment]
@ErfolgreichCharismatisch ,
Can you please paste here the output of `df.head()` ?

**Comment by ErfolgreichCharismatisch** [comment]
```
Empty DataFrame
Columns: [title, paragraphs]
Index: []
```

**Comment by andrelmfarias** [comment]
Thanks, we will take a look at it.

**Comment by andrelmfarias** [comment]
@ErfolgreichCharismatisch 
Could you please test pdf_converter on a folder with no subfolders and only pdf files (preferably some of the pdf files you already have in the folder)?

**Comment by ErfolgreichCharismatisch** [comment]
To check functionality, I wrote my own pdf to csv-parser and converted each file to a line.
It showed this behaviour

```
[22/Jul/2019 15:28:28] WARNING - The pre-trained model you are loading is an uncased model but you have set `do_lower_case` to False. We are setting `do_lower_case=True` for you but you may want to check this behavior.
[22/Jul/2019 15:28:29] INFO - loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\....pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
```
And it returned to the windows prompt. Without a result and without an error message.
Can you explain?

**Comment by andrelmfarias** [comment]
This warning is expected and I am currently working to avoid that in a next PR. 

However, this should not affect inference or performance of the `cdqa_pipeline`. No output from `cdqa_pipeline.predict()` is a really strange behaviour, even with this warnings...

Did you make sure the elements in the `paragraphs` column in your `.csv` file are written as lists of paragraphs?

**Comment by ErfolgreichCharismatisch** [comment]
Here is an example paragraph from books.csv

```
date,title,category,link,abstract,paragraphs
"","title.pdf","none","E:/books\title.pdf","","['Volume II','Table of Contents','Message to the Reader','3',....,'']"
```

**Comment by ErfolgreichCharismatisch** [comment]
Instead of 

```
df = pd.read_csv('books.csv', converters={'paragraphs': literal_eval},encoding='utf-8')
cdqa_pipeline = QAPipeline(**reader**='models/bert_qa_vGPU-sklearn.joblib', max_df=1.0)
cdqa_pipeline.fit(X=df)   
cdqa_pipeline.predict(X='What is?')
```

I tried

```
df = pd.read_csv('books.csv', converters={'paragraphs': literal_eval},encoding='utf-8')
cdqa_pipeline = QAPipeline(**model**='models/bert_qa_vGPU-sklearn.joblib', max_df=1.0)
cdqa_pipeline.fit(X=df)   
cdqa_pipeline.predict(X='What is?')
```

and got

```
[22/Jul/2019 20:20:52] INFO - loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at C:\...\.pytorch_pretrained_bert\distributed_-1\9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
[22/Jul/2019 20:20:52] INFO - extracting archive file C:\...\.pytorch_pretrained_bert\distributed_-1\9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir C:\Users\...\AppData\Local\Temp\tmpasnkpknm
[22/Jul/2019 20:20:57] INFO - Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

[22/Jul/2019 20:21:02] INFO - Weights of BertForQuestionAnswering not initialized from pretrained model: ['qa_outputs.bias', 'qa_outputs.weight']
[22/Jul/2019 20:21:02] INFO - Weights from pretrained model not used in BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
3it [00:00, 176.56it/s]
[22/Jul/2019 20:21:15] WARNING - The pre-trained model you are loading is an uncased model but you have set `do_lower_case` to False. We are setting `do_lower_case=True` for you but you may want to check this behavior.
[22/Jul/2019 20:21:16] INFO - loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\...\.pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
```

**Comment by andrelmfarias** [comment]
I uploaded a new version of the GPU model. Can you please download it in the link below and run your script on `books.csv` ? (Using **reader**, not **model**, in the QAPipeline arguments)

https://github.com/cdqa-suite/cdQA/releases/download/bert_qa_vGPU/bert_qa_vGPU-sklearn.joblib

If it doesn't work can you please download the [CPU version](https://github.com/cdqa-suite/cdQA/releases/download/bert_qa_vCPU/bert_qa_vCPU-sklearn.joblib) and run the script below (load CPU version and send it to GPU with the method `.cuda()`)?

```
df = pd.read_csv('books.csv', converters={'paragraphs': literal_eval},encoding='utf-8')
cdqa_pipeline = QAPipeline(reader='models/bert_qa_vCPU-sklearn.joblib', max_df=1.0)
cdqa_pipeline.cuda()
cdqa_pipeline.fit(X=df)   
cdqa_pipeline.predict(X='What is?') 
```

**Comment by ErfolgreichCharismatisch** [comment]
```
(frageantwort) PS E:\cdQA> python train.py
3it [00:00, 63.99it/s]
[23/Jul/2019 14:46:26] WARNING - The pre-trained model you are loading is an uncased model but you have set `do_lower_case` to False. We are setting `do_lower_case=True` for you but you may want to check this behavior.
[23/Jul/2019 14:46:28] INFO - loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\...\.pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
(frageantwort) PS E:\cdQA>
```
Current code

```
df = pd.read_pickle('E:/books.pkl')
cdqa_pipeline = QAPipeline(reader='models/bert_qa_vCPU-sklearn.joblib', max_df=1.0)
cdqa_pipeline.cuda()
cdqa_pipeline.fit(X=df)   
cdqa_pipeline.predict(X='What is?') 
```
The same with `cdqa_pipeline = QAPipeline(reader='models/bert_qa_vGPU-sklearn.joblib', max_df=1.0)`

**Comment by andrelmfarias** [comment]
@ErfolgreichCharismatisch 

I think I understand why your script is not outputting anything. You need to print out the output of `cdqa_pipeline.predict()` (as shown in our [tutorial](https://github.com/cdqa-suite/cdQA/blob/master/examples/tutorial-first-steps-cdqa.ipynb))

```
prediction = cdqa_pipeline.predict(X='What is?')

print('query: {}'.format(query))
print('answer: {}'.format(prediction[0]))
print('title: {}'.format(prediction[1]))
print('paragraph: {}'.format(prediction[2]))
```

**Comment by ErfolgreichCharismatisch** [comment]
Thanks for supporting me all the way. 

It gives me interestingly deep answers; I asked: "Who is Sherlock Holmes?" and it answered with "who are you".

Now the question is about ground truth. What should the answer be? How do I realize that the system does not have an answer - apart from the answer being gibberish at first look.

**Comment by andrelmfarias** [comment]
> It gives me interestingly deep and somewhat eerie answers; I asked: "Who is Sherlock Holmes?" and it answered with "who are you".
> EDIT: I tried more questions. Your software gives quite insightful answers.

Its answers really depends on you the documents on your database actually. Maybe they are insightful because your documents are insightful

> How do I realize that the system does not have an answer - apart from the answer being gibberish at first look.

You can use the logits sent with the answer (feature added with PR #203 ) and fine tune a threshold as proposed on #195

**Comment by ErfolgreichCharismatisch** [comment]
Does it work with documents of different languages?

**Comment by andrelmfarias** [comment]
For now, it works only for English. Depending on the language, you can use the BERT version for that specific language as Reader, but you will need to train it on a QA dataset for that language...
