### ISSUE TITLE
No module named 'tqdm.autonotebook'

### ISSUE THREAD

**Issue by amnsr17** [cdqa-suite/cdQA#265]
I am importing QAPipeline using this:
`from cdqa.pipeline import QAPipeline`
I am getting this error: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/flash/abdullah/projects/cdQA/cdqa/pipeline/__init__.py", line 1, in <module>
    from .cdqa_sklearn import QAPipeline
  File "/home/flash/abdullah/projects/cdQA/cdqa/pipeline/cdqa_sklearn.py", line 12, in <module>
    from cdqa.reader import BertProcessor, BertQA
  File "/home/flash/abdullah/projects/cdQA/cdqa/reader/__init__.py", line 1, in <module>
    from .bertqa_sklearn import BertQA, BertProcessor
  File "/home/flash/abdullah/projects/cdQA/cdqa/reader/bertqa_sklearn.py", line 36, in <module>
    from tqdm.autonotebook import tqdm, trange
ModuleNotFoundError: No module named 'tqdm.autonotebook'`
Any help??

**Comment by andrelmfarias** [comment]
You should be sure you are using the last version of `tqdm`. So can you please try to update `tqdm` by running `pip install tqdm -U` ?

**Comment by amnsr17** [comment]
@andrelmfarias worked as a charm! tqdm was not updated. Thanks a lot for fast replying.
