### ISSUE TITLE
Try to use "xlnet_cased_vCPU.joblib" and getting error

### ISSUE THREAD

**Issue by morningstar899** [cdqa-suite/cdQA#279]
Try to use "export reader_path=/home/xxxxxx/bert_qa_vGPU-sklearn.joblib" and bring server up by "FLASK_APP=api.py flask run -h 0.0.0.0",  I got error as below: 
"_Error: While importing "api", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/App/cdQA/api.py", line 20, in <module>
    cdqa_pipeline = QAPipeline(reader=reader_path)
  File "/App/cdQA/cdqa/pipeline/cdqa_sklearn.py", line 82, in __init__
    self.reader = joblib.load(reader)
  File "/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'cdqa.reader.reader_sklearn'"_

**Comment by andrelmfarias** [comment]
Hi @morningstar899 ,

You shouldn't be using the `xlnet_cased_vCPU.joblib` it's broken and not performing well, we will probably exclude it from the releases.

You should be using the CPU and GPU versions of BERT

Thanks
