### ISSUE TITLE
CDQA API pdf_converter  Unexpected error: class 'AttributeError  Unable to process file ....pdf 

### ISSUE THREAD

**Issue by infact** [cdqa-suite/cdQA#354]
I am trying to get the [cdQA API](https://github.com/cdqa-suite/cdQA/blob/master/api.py) to handle pdf files. I placed some pdf files into ..data/pdf folder. But I ran into errors with pdf_converter . cdqa pdf_converter Unexpected error: class 'AttributeError  Any one please help me understand what's wrong with my code below.

```
from flask import Flask, request, jsonify
from flask_cors import CORS
import torch
import os
from ast import literal_eval
import pandas as pd
from cdqa.utils.converters import pdf_converter
from cdqa.utils.filters import filter_paragraphs
from cdqa.utils.download import download_model
from cdqa.pipeline import QAPipeline
from flask import make_response

app = Flask(__name__)
CORS(app)
def application(environ, start_response):
    if environ['REQUEST_METHOD'] == 'OPTIONS':
        start_response(
    '200 OK',
    [
        ('Content-Type', 'application/json'),
        ('Access-Control-Allow-Origin', '*'),
        ('Access-Control-Allow-Headers', 'Authorization, Content-Type'),
        ('Access-Control-Allow-Methods', 'GET','POST'),
    ]
    )
    return ''
os.environ["dataset_path"]='./data/pdf/'
os.environ["reader_path"]="./models/bert_qa.joblib"

dataset_path = os.environ["dataset_path"]
reader_path = os.environ["reader_path"]

df = pdf_converter(directory_path='./data/pdf/')
df = filter_paragraphs(df)

cdqa_pipeline = QAPipeline(reader=reader_path)
cdqa_pipeline.fit_retriever(df=df)

@app.route("/api", methods=["GET"])
def api():
    query = request.args.get("query")
    print(query)
    prediction = cdqa_pipeline.predict(query=query)
    return jsonify(
        query=query, answer=prediction[0], title=prediction[1], paragraph=prediction[2]
    )

if __name__ == '__main__':
    app.run(debug=True) 
```

**### Error message goes below**

```
Unexpected error: <class 'AttributeError'>
Unable to process file 1q19-pr-12648.pdf
Unexpected error: <class 'AttributeError'>
Unable to process file 4q17-pr.pdf
Unexpected error: <class 'AttributeError'>
Unable to process file 4q18-pr2.pdf
Traceback (most recent call last):
  File "c:/Users/..y/AppData/Local/Continuum/anaconda3/envs/api_cdqa_1/cdqa/pdfreadtest3.py", line 35, in <module>
    df = filter_paragraphs(df)
  File "c:\Users\..\AppData\Local\Continuum\anaconda3\envs\api_cdqa_1\cdqa\cdqa\utils\filters.py", line 52, 
in filter_paragraphs
    articles["paragraphs"] = articles["paragraphs"].apply(replace_and_split)
  File "C:\Users\..\AppData\Local\Continuum\anaconda3\envs\api_cdqa_1\lib\site-packages\pandas\core\series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "c:\Users\..\AppData\Local\Continuum\anaconda3\envs\api_cdqa_1\cdqa\cdqa\utils\filters.py", line 37, 
in replace_and_split
    for paragraph in paragraphs:
TypeError: 'NoneType' object is not iterable
```

**Comment by waterman1** [comment]
Please close this issue.

**Comment by infact** [comment]
Those error messages are confusing. I resolved this issue by uninstalling and reinstalling all required packages.
